name: Deploy to Neocities
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          # provide the secret under multiple keys to support different action versions
          apiKey: ${{ secrets.NEOCITIES_API_TOKEN }}
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          dist_dir: public
          cleanup: false
